target:

U_SPI_HOME=../..
include $(U_SPI_HOME)/makefiles/config/config.mk

U_INCLUDES=-I../lib

U_DEP_LIBS=\
../lib/$(G_BUILD_DIR)/$(G_LIB_PFX)test-inner$(G_LIB_EXT)

U_LIBS:=$(U_DEP_LIBS)

include $(U_SPI_HOME)/makefiles/spi/dll.mk


