target:

U_MAKEFILES=..

include $(U_MAKEFILES)/config/config.mk

U_SRC_DIR=src
U_INC_DIR=src
U_TARGET=cversion

include $(U_MAKEFILES)/build/exe.mk

U_VCPROJ=cversion
U_VCPROJ_OPTIONS=-trun --cleanTarget=config-clean

