#if defined _MSC_VER && _MSC_VER >= 1600
#include <stdint.h>
#endif


#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyConfigFlexLexer

#ifdef yyalloc
#define yyConfigalloc_ALREADY_DEFINED
#else
#define yyalloc yyConfigalloc
#endif

#ifdef yyrealloc
#define yyConfigrealloc_ALREADY_DEFINED
#else
#define yyrealloc yyConfigrealloc
#endif

#ifdef yyfree
#define yyConfigfree_ALREADY_DEFINED
#else
#define yyfree yyConfigfree
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types.
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t;
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)

/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::streambuf* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 59
#define YY_END_OF_BUFFER 60
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[248] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       60,   58,    1,    1,   56,   58,   42,   56,   58,   56,
       56,   56,    2,   56,   57,   57,   57,   58,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       51,   50,   55,   54,   55,   48,   47,   48,   44,   43,
        0,    8,    0,    0,    0,    0,    0,    0,    0,    0,
        2,    4,   52,   49,    0,    2,    0,   41,   57,   57,
       57,   57,   57,    0,    7,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   53,   46,    8,    0,

        0,    0,    0,    0,    5,    0,    5,   45,    0,    0,
        4,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   16,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,    0,    0,
        0,    0,    0,    6,    0,   57,   57,    9,   15,   57,
       57,   57,   57,   28,   57,   57,   17,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       22,    0,    0,    0,    0,    0,    3,   23,   33,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,    0,    0,    0,    0,

        0,   57,   19,   29,   57,   57,   57,   57,   36,   21,
       30,   20,   24,   57,   57,   57,   57,   57,   14,   12,
        0,   11,    0,   57,   57,   35,   57,   57,   40,   57,
       25,   57,   57,   31,   10,   13,   32,   37,   38,   34,
       57,   26,   27,   18,   57,   39,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    4,    8,    4,
        4,    9,   10,    4,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,    4,    4,
        4,    4,    4,    1,   16,   17,   17,   17,   18,   19,
       17,   17,   17,   17,   17,   20,   17,   17,   17,   17,
       17,   21,   22,   23,   24,   17,   17,   17,   17,   17,
        4,   25,    4,    4,   26,   27,   28,   29,   30,   31,

       32,   33,   34,   35,   36,   17,   17,   37,   38,   39,
       40,   41,   17,   42,   43,   44,   45,   46,   17,   47,
       48,   49,    4,    4,    4,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[50] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    3,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3
    } ;

static const flex_int16_t yy_base[257] =
    {   0,
        0,    0,  305,  304,   47,   48,   49,   50,  303,  302,
      304,  309,  309,  309,  309,   49,  309,   28,  278,   49,
      288,   56,   61,  286,    0,   39,   41,  273,   41,   45,
       41,  271,  259,  257,  255,   42,   46,   54,  256,   55,
      309,  309,  309,  309,  281,  309,  309,  280,  309,  309,
       84,  309,   87,  245,   59,  251,  258,  281,  280,  273,
       87,   86,  277,  309,  271,   96,  106,  309,    0,  264,
      246,  258,  236,  253,  252,  250,  249,  237,  238,  229,
      228,  228,  234,  226,  230,  236,   75,  238,  217,   85,
      227,  219,  222,  219,  219,  224,  309,  309,   98,  218,

      217,  227,  225,  213,  309,  246,  245,  309,  110,  238,
      237,  228,  206,  230,  215,  204,  202,  201,  211,  213,
      203,  208,  196,    0,  204,  195,  190,   81,  198,  202,
      189,   90,  191,  199,  198,  193,  184,  196,  186,  185,
      187,  178,  176,  309,  207,  202,  187,    0,    0,  175,
      173,  182,  178,    0,  172,  181,    0,  184,  183,  178,
      177,  172,  181,  170,  166,  174,  166,   98,  168,  156,
        0,  158,  157,  153,  160,  160,  181,    0,    0,  166,
      161,  153,  147,  146,  147,  158,  157,  142,  155,  150,
      139,  154,  149,  152,  140,  150,  133,  132,  144,  142,

      143,  128,    0,    0,  131,  138,  125,  124,  152,    0,
        0,    0,    0,  122,  132,  126,  131,  125,  309,  309,
      128,  309,  125,  122,   94,  119,   85,  100,  309,   99,
        0,   98,   75,    0,  309,  309,    0,    0,  309,    0,
       63,    0,    0,    0,   55,  309,  309,  137,  140,  143,
      146,  149,  152,   65,  155,  158
    } ;

static const flex_int16_t yy_def[257] =
    {   0,
      247,    1,  248,  248,  249,  249,  250,  250,  251,  251,
      247,  247,  247,  247,  247,  252,  247,  247,  253,  247,
      247,  247,  247,  247,  254,  254,  254,  255,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      252,  247,  252,  247,  247,  247,  247,  247,  256,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  254,  254,
      254,  254,  254,  255,  255,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  247,  247,  252,  247,

      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  247,  247,
      247,  247,  247,  247,  247,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  247,  247,  247,  247,  247,  247,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  247,  247,  247,  247,

      247,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  247,  247,
      247,  247,  247,  254,  254,  254,  254,  254,  247,  254,
      254,  254,  254,  254,  247,  247,  254,  254,  247,  254,
      254,  254,  254,  254,  254,  247,    0,  247,  247,  247,
      247,  247,  247,  247,  247,  247
    } ;

static const flex_int16_t yy_nxt[359] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   15,   15,
       20,   21,   22,   23,   24,   25,   25,   25,   26,   25,
       25,   25,   27,   25,   12,   25,   28,   25,   25,   29,
       30,   31,   32,   25,   25,   33,   34,   25,   25,   35,
       36,   25,   37,   38,   39,   40,   25,   25,   25,   44,
       44,   47,   47,   52,   70,   45,   45,   48,   48,   54,
       60,   72,   61,   55,   63,   56,   71,   69,   64,  246,
       57,   65,   60,   53,   66,   76,   79,   77,   67,   81,
       78,   89,   73,   87,   80,   91,   88,   82,   52,   90,
       95,   99,   67,  245,   96,   92,  101,  102,   60,   62,

       61,   93,   52,   67,   67,  244,   65,   60,   53,   66,
      127,   53,  131,   67,  128,  110,  110,   67,   67,  111,
      145,  160,   53,  109,  161,  165,  132,   67,  193,  243,
      242,  241,  240,  239,  166,  238,  194,   41,   41,   41,
       43,   43,   43,   46,   46,   46,   49,   49,   49,   51,
       51,   51,   58,  237,   58,   74,  236,   74,  106,  235,
      106,  234,  233,  232,  231,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  217,  216,
      215,  214,  213,  212,  211,  210,  209,  208,  207,  206,
      205,  204,  203,  202,  177,  201,  200,  199,  198,  197,

      196,  195,  192,  191,  190,  189,  188,  187,  186,  185,
      184,  183,  148,  182,  181,  180,  179,  178,  148,  148,
      177,  176,  175,  174,  173,  172,  171,  170,  169,  168,
      148,  167,  164,  163,  162,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  150,  149,  148,  148,  147,  146,
      111,  111,  144,  144,  143,  142,  141,  140,  139,  138,
      137,  136,  135,  134,  133,  130,  129,  126,  125,  124,
      123,  122,  121,  120,  119,  118,  117,  116,   75,   75,
      115,  114,  113,  112,  109,  108,   62,  107,  105,  104,
      103,  100,   98,   97,   94,   86,   85,   84,   83,   75,

       68,   62,   59,  247,   50,   50,   42,   42,   11,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247
    } ;

static const flex_int16_t yy_chk[359] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        6,    7,    8,   16,   26,    5,    6,    7,    8,   18,
       20,   27,   20,   18,   22,   18,   26,  254,   22,  245,
       18,   23,   23,   16,   23,   29,   30,   29,   23,   31,
       29,   37,   27,   36,   30,   38,   36,   31,   51,   37,
       40,   53,   23,  241,   40,   38,   55,   55,   61,   62,

       61,   38,   99,   62,   61,  233,   66,   66,   51,   66,
       87,   53,   90,   66,   87,   67,   67,   62,   61,   67,
      109,  128,   99,  109,  128,  132,   90,   66,  168,  232,
      230,  228,  227,  226,  132,  225,  168,  248,  248,  248,
      249,  249,  249,  250,  250,  250,  251,  251,  251,  252,
      252,  252,  253,  224,  253,  255,  223,  255,  256,  221,
      256,  218,  217,  216,  215,  214,  209,  208,  207,  206,
      205,  202,  201,  200,  199,  198,  197,  196,  195,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  177,  176,  175,  174,  173,  172,

      170,  169,  167,  166,  165,  164,  163,  162,  161,  160,
      159,  158,  156,  155,  153,  152,  151,  150,  147,  146,
      145,  143,  142,  141,  140,  139,  138,  137,  136,  135,
      134,  133,  131,  130,  129,  127,  126,  125,  123,  122,
      121,  120,  119,  118,  117,  116,  115,  114,  113,  112,
      111,  110,  107,  106,  104,  103,  102,  101,  100,   96,
       95,   94,   93,   92,   91,   89,   88,   86,   85,   84,
       83,   82,   81,   80,   79,   78,   77,   76,   75,   74,
       73,   72,   71,   70,   65,   63,   60,   59,   58,   57,
       56,   54,   48,   45,   39,   35,   34,   33,   32,   28,

       24,   21,   19,   11,   10,    9,    4,    3,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[60] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
/*

    Sartorial Programming Interface (SPI) code generators
    Copyright (C) 2012-2023 Sartorial Programming Ltd.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

*/
/*
 * Lexical analyzer for the SPI configuration file format
 *
 * We need to recognize integers, dates, strings, real numbers, identifiers
 * and various bits of punctuation and keywords from the parser.
 *
 * In addition we need to be able to extract a verbatim block - what this
 * will do is extract from the code until a terminating separator is
 * detected.
 */

#include <spi/platform.h>
#include "configLexer.hpp"
#include <spi/StringUtil.hpp>

#include <stdarg.h> // for variable argument list methods
#include <string.h> // for strdup etc

#ifdef _MSC_VER
/* this disables the warning message about dividing by zero */
#pragma warning( disable : 4723 )
#define YY_NO_UNISTD_H
#define strdup _strdup
#endif

#define YY_DECL int ConfigLexer::getToken(TokenValue *tokenValue)
#define YY_USER_ACTION if (m_inVerbatim) { m_verbatim << yytext; }

using namespace std; // to get cin and cout

// we will have various states in addition to the normal state (INITIAL)
// these are CPP_COMMENT, C_COMMENT, DESCRIPTION, COMMAND



#define INITIAL 0
#define CPP_COMMENT 1
#define C_COMMENT 2
#define DESCRIPTION 3
#define COMMAND 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin.rdbuf(std::cin.rdbuf());

		if ( ! yyout )
			yyout.rdbuf(std::cout.rdbuf());

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{



	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 248 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 309 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )

    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
; /* ignore whitespace */
	YY_BREAK
/*
 * Integers - positive or negative.
 */
case 2:
YY_RULE_SETUP
{
    tokenValue->anInt = atoi(yytext);
    dprintf ("INT: %ld\n", tokenValue->anInt);
    return SPI_CONFIG_TOKEN_TYPE_INT;
}
	YY_BREAK
/*
 * Dates - YYYY-MM-DD
 */
case 3:
YY_RULE_SETUP
{
    tokenValue->aDate = stringToDate(yytext);
    dprintf ("DATE: %s\n", yytext);
    return SPI_CONFIG_TOKEN_TYPE_DATE;
}
	YY_BREAK
/*
 * Doubles - positive or negative, with optional exponent.
 */
case 4:
YY_RULE_SETUP
{
    char* ep;
    tokenValue->aDouble = strtod(yytext, &ep);
    // we should check that ep points at the end of the yytext
    // it ought to be ok since yytext is of the correct pattern
    dprintf ("DOUBLE: %f\n", tokenValue->aDouble);
    return SPI_CONFIG_TOKEN_TYPE_DOUBLE;
}
	YY_BREAK
/*
 * Single characters represented in C-style within single quotes.
 *
 * We won't allow these to be escaped - when we have a char we
 * really expect it to be printable.
 */
case 5:
YY_RULE_SETUP
{
    tokenValue->aChar = yytext[1];
    dprintf ("CHAR: %c\n", tokenValue->aChar);
    return SPI_CONFIG_TOKEN_TYPE_CHAR;
}
	YY_BREAK
/*
 * Single characters supporting escaping - designed for use solely within
 * verbatim C++ code.
 */
case 6:
YY_RULE_SETUP
{
    tokenValue->aCharEscape = yytext[2];
    dprintf("CHAR_ESCAPE: %c\n", tokenValue->aCharEscape);
    return SPI_CONFIG_TOKEN_TYPE_CHAR_ESCAPE;
}
	YY_BREAK
/*
  * Expressions are like in a Unix-style shell - enclosed by ``
  */
case 7:
YY_RULE_SETUP
{
    yytext[strlen(yytext)-1] = '\0';
    try
    {
        std::string expr = spi::StringCapture(yytext+1);
        tokenValue->anExpression = strdup(expr.c_str());
    }
    catch (std::exception &e)
    {
        error_handler("%s\n", e.what());
    }
    return SPI_CONFIG_TOKEN_TYPE_EXPRESSION;
}
	YY_BREAK
/*
 * Strings - we do not allow strings to be continued over a line
 */
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
{
    if (yytext[yyleng-1] != '"')
    {
        error_handler ("Unterminated character string %s", yytext);
    }
    else
    {
        yytext[yyleng-1] = '\0';
        try
        {
            std::string str = spi::StringCapture(yytext+1);
            tokenValue->aString = strdup(str.c_str());
            dprintf ("STRING: %s\n", tokenValue->aString);
        }
        catch (std::exception &e)
        {
            error_handler("%s\n", e.what());
        }
    }
    return SPI_CONFIG_TOKEN_TYPE_STRING;
}
	YY_BREAK
/*
  * Boolean values can use true, True, TRUE, false, False or FALSE
  */
case 9:
YY_RULE_SETUP
{
    tokenValue->aBool = (yytext[0] == 't' || yytext[0] == 'T');
    dprintf ("BOOL: %d\n", tokenValue->aBool);
    return SPI_CONFIG_TOKEN_TYPE_BOOL;
}
	YY_BREAK
/*
  * Keywords just return the keyword
  *
  * Special language keywords begin with %
  * Keywords borrowed from c++ are as is
  * Some primitive types which are not primitive c++ types are treated
  * as keywords - e.g. string, Date, size_t
  */
case 10:
case 11:
case 12:
case 13:
case 14:
case 15:
case 16:
case 17:
case 18:
case 19:
case 20:
case 21:
case 22:
case 23:
case 24:
case 25:
case 26:
case 27:
case 28:
case 29:
case 30:
case 31:
case 32:
case 33:
case 34:
case 35:
case 36:
case 37:
case 38:
case 39:
case 40:
case 41:
YY_RULE_SETUP
{
    tokenValue->aKeyword = strdup(yytext);
    return SPI_CONFIG_TOKEN_TYPE_KEYWORD;
}
	YY_BREAK
/*
  * commands begin with # and go to the end of the line
  */
case 42:
YY_RULE_SETUP
{
    BEGIN(COMMAND);
    clear_buffer();
}
	YY_BREAK
/*
  * command ends with new line
  */
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
{
    tokenValue->aCommand = strdup(m_buffer.str().c_str());
    dprintf ("COMMAND: %s\n", tokenValue->aCommand);
    clear_buffer();
    BEGIN(INITIAL);
    return SPI_CONFIG_TOKEN_TYPE_COMMAND;
}
	YY_BREAK
/*
  * any character within the COMMAND state is appended to the buffer
  */
case 44:
YY_RULE_SETUP
m_buffer << yytext[0];
	YY_BREAK
/*
  * doxygen style c-comments are treated as description
  * they start with / ** and go to the matching end comment
  */
case 45:
YY_RULE_SETUP
{
    BEGIN(DESCRIPTION);
    clear_buffer();
}
	YY_BREAK
/*
  * doxygen style comments end with the end comment
  * we are not so sophisticated that we check whether they are part of a string
  */
case 46:
YY_RULE_SETUP
{
    tokenValue->aDescription = strdup(m_buffer.str().c_str());
    dprintf ("DESCRIPTION: %s\n", tokenValue->aDescription);
    clear_buffer();
    BEGIN(INITIAL);
    return SPI_CONFIG_TOKEN_TYPE_DESCRIPTION;
}
	YY_BREAK
/*
  * new lines in the DESCRIPTION state are appended to the buffer
  */
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
m_buffer << std::endl;
	YY_BREAK
/*
  * any character in the DESCRIPTION state is appended to the buffer
  */
case 48:
YY_RULE_SETUP
m_buffer << yytext[0];
	YY_BREAK
/*
  * c++ comments begin with // and go to the end of the line
  */
case 49:
YY_RULE_SETUP
BEGIN(CPP_COMMENT);
	YY_BREAK
/*
  * the c++ comment ends with new line - the contents are ignored
  */
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
BEGIN(INITIAL);
	YY_BREAK
/*
 * c++ comments are completely ignored
 */
case 51:
YY_RULE_SETUP

	YY_BREAK
/*
 * c-comments are treated the same as c++-comments
 * they are ignored unless they are also doxygen style comments which are
 * processed first in this list (is that relevant or is lex clever enough
 * to find the maximum length text that matches a rule?
 */
case 52:
YY_RULE_SETUP
BEGIN(C_COMMENT);
	YY_BREAK
/*
  * c-comments end with the end of comment sequence
  */
case 53:
YY_RULE_SETUP
BEGIN(INITIAL);
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP

	YY_BREAK
/*
 * c comments are completely ignored
 */
case 55:
YY_RULE_SETUP

	YY_BREAK
/*
  * We will support various punctuation marks as follows:
  * !%^&*()-+={[}]:;~#|<,>.?/
  *
  * (typed in from a QWERTY keyboard from top left to bottom right)
  *
  * Some of these are needed for verbatim code which we tokenize when
  * searching for the end of the block.
  */
case 56:
YY_RULE_SETUP
{
    dprintf ("PUNCT: %s\n", yytext);
    return yytext[0]; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CPP_COMMENT):
case YY_STATE_EOF(C_COMMENT):
case YY_STATE_EOF(DESCRIPTION):
case YY_STATE_EOF(COMMAND):
{
    yyterminate();
}
	YY_BREAK
/* name - valid C/C++ identifier and defined after all the keywords */
case 57:
YY_RULE_SETUP
{
    tokenValue->aName = strdup(yytext);
    dprintf ("NAME: %s\n", tokenValue->aName);
    return SPI_CONFIG_TOKEN_TYPE_NAME;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
{
    error_handler ("Invalid character %c\n", yytext[0]);
    return 0;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
ECHO;
	YY_BREAK

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	yy_state_type yy_current_state;
	char *yy_cp;

	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 248 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 248 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 247);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    void yyFlexLexer::yyunput( int c, char* yy_bp)
{
	char *yy_cp;

    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif

    int yyFlexLexer::yyinput()
{
	int c;

	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )

    yylineno++;
;

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 *
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream& input_file )
{

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 *
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 *
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 *
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 *
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 *
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )

{
	int oerrno = errno;

	yy_flush_buffer( b );

	b->yy_input_file = file.rdbuf();
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 *
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	yy_size_t num_to_alloc;

	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"



 /*
 * We should not get here
 */
int yyFlexLexer::yylex()
{
    fprintf (stderr, "%s: should not get here!\n", __FUNCTION__);
    exit (1);
}

/*
** This function handles the condition where we reach the end of a file
** and need to start again.
*/
int yyFlexLexer::yywrap(void)
{
    return 1; /* no more files */
}

void ConfigLexer::error_handler(const char *format, ...)
{
    ++num_errors;
    fprintf (stderr, "%s(%d): error: ", filename.c_str(), lineno());
    va_list ap;
    va_start (ap, format);
    vfprintf (stderr, format, ap);
    va_end (ap);
}

void ConfigLexer::dprintf(const char* format, ...)
{
#if YYDEBUG
    va_list ap;
    va_start (ap, format);
    vprintf (format, ap);
    va_end (ap);
#endif
}

int ConfigLexer::stringToDate (const char* str)
{
    try
    {
        spi::Date date = spi::Date::FromString(str);
        return (int)date;
    } catch (std::exception&) {
        error_handler ("Could not convert %s to date\n", str);
        return -1;
    }
}

ConfigLexer::ConfigLexer (const std::string &arg_filename,
                          std::istream      *arg_yyin,
                          std::ostream      *arg_yyout)
:
yyFlexLexer(arg_yyin, arg_yyout),
    filename(arg_filename),
    num_errors(0),
    token_stack(),
    m_buffer(),
    m_inVerbatim(false),
    m_verbatim()
{}

ConfigLexer::~ConfigLexer() {}

ConfigLexer::Token ConfigLexer::getToken()
{
    if (token_stack.size() > 0)
    {
        Token token = token_stack.back();
        token_stack.pop_back();
        return token;
    }
    int tokenType;
    TokenValue tokenValue;
    tokenType = getToken(&tokenValue);
    Token token(tokenType, tokenValue);

    return token;
}

void ConfigLexer::returnToken(Token &token)
{
    token_stack.push_back(token);
}


namespace {

    ConfigLexer::TokenValue TokenValueCopy(
        int                     tokenType,
        ConfigLexer::TokenValue value)
    {
        ConfigLexer::TokenValue copy;

        switch (tokenType)
        {
        case SPI_CONFIG_TOKEN_TYPE_STRING:
        case SPI_CONFIG_TOKEN_TYPE_NAME:
        case SPI_CONFIG_TOKEN_TYPE_KEYWORD:
        case SPI_CONFIG_TOKEN_TYPE_DESCRIPTION:
        case SPI_CONFIG_TOKEN_TYPE_EXPRESSION:
        case SPI_CONFIG_TOKEN_TYPE_COMMAND:
            /* copying the string is the same as copying any char* member
               of the union! */
            copy.aString = strdup(value.aString);
            break;
        default:
            copy = value;
            break;
        }
        return copy;
    }

    void TokenValueFree(
        int                     tokenType,
        ConfigLexer::TokenValue value)
    {
        switch(tokenType)
        {
        case SPI_CONFIG_TOKEN_TYPE_STRING:
        case SPI_CONFIG_TOKEN_TYPE_NAME:
        case SPI_CONFIG_TOKEN_TYPE_KEYWORD:
        case SPI_CONFIG_TOKEN_TYPE_DESCRIPTION:
        case SPI_CONFIG_TOKEN_TYPE_EXPRESSION:
        case SPI_CONFIG_TOKEN_TYPE_COMMAND:
            /* freeing the string is the same as freeing any char* member
               of the union */
            free(value.aString);
            break;
        default:
            break; // do nothing
        }
        memset(&value, 0, sizeof(ConfigLexer::TokenValue));
    }

} // end of anonymous namespace

ConfigLexer::Token::Token (int tokenType, TokenValue tokenValue)
    :
    type(tokenType),
    value(tokenValue)
{}

ConfigLexer::Token::Token ()
{
    type          = 0;
    value.aDouble = 0.0;
}

ConfigLexer::Token::~Token()
{
    TokenValueFree(type, value);
}

ConfigLexer::Token::Token (const Token &other)
{
    type  = other.type;
    value = TokenValueCopy(other.type, other.value);
}

ConfigLexer::Token& ConfigLexer::Token::swap (ConfigLexer::Token &other)
{
    std::swap(type, other.type);
    std::swap(value, other.value);
    return *this;
}

ConfigLexer::Token& ConfigLexer::Token::operator= (const Token &other)
{
    ConfigLexer::Token tmp(other);
    swap(tmp);
    return *this;
}

std::string ConfigLexer::Token::toString() const
{
    switch (type)
    {
    case SPI_CONFIG_TOKEN_TYPE_INT:
        return spi::StringFormat("%d", value.anInt);
    case SPI_CONFIG_TOKEN_TYPE_DATE:
        return std::string(spi::Date(value.aDate));
    case SPI_CONFIG_TOKEN_TYPE_DOUBLE:
        return spi::StringFormat("%f", value.aDouble);
    case SPI_CONFIG_TOKEN_TYPE_CHAR:
        return spi::StringFormat("'%c'", value.aChar);
    case SPI_CONFIG_TOKEN_TYPE_STRING:
        return spi::StringFormat("\"%s\"", value.aString);
    case SPI_CONFIG_TOKEN_TYPE_BOOL:
        return std::string(value.aBool ? "true" : "false");
    case SPI_CONFIG_TOKEN_TYPE_NAME:
        return std::string(value.aName);
    case SPI_CONFIG_TOKEN_TYPE_KEYWORD:
        return std::string(value.aKeyword);
    case SPI_CONFIG_TOKEN_TYPE_DESCRIPTION:
        return spi::StringFormat("/**%s*/", value.aDescription);
    case SPI_CONFIG_TOKEN_TYPE_EXPRESSION:
        return spi::StringFormat("%s", value.anExpression);
    case SPI_CONFIG_TOKEN_TYPE_COMMAND:
        return spi::StringFormat("#%s", value.aCommand);
    case SPI_CONFIG_TOKEN_TYPE_CHAR_ESCAPE:
        return spi::StringFormat("'\\%c'", value.aCharEscape);
    case 0:
        return std::string("EOF");
    }
    return spi::StringFormat("%c", type);
}

std::ostream& operator << (std::ostream& os, const ConfigLexer::Token& token)
{
    os << token.toString();
    return os;
}

void ConfigLexer::clear_buffer()
{
    m_buffer.clear();
    m_buffer.str(std::string());
}

VerbatimConstSP ConfigLexer::getVerbatim(
    char incrementor,
    char terminator,
    const char* extras)
{
    int lineNumber = getLineNumber();

    // initialise capture of all text before it gets put into a token
    m_inVerbatim = true;
    m_verbatim.str(std::string());

    Token token = getToken();
    int level = 0;

    while (token.type)
    {
        if (token.type == incrementor)
        {
            ++level;
        }
        else if (token.type == terminator)
        {
            if (level == 0)
                break;
            --level;
        }
        token = getToken();
    }

    if (token.type != terminator)
    {
        error_handler("Unterminated code block - EOF before matching %c\n",
            terminator);
        // throw std::runtime_error("Could not get VERBATIM code");
        return VerbatimConstSP();
    }

    m_verbatim << extras;
    m_inVerbatim = false;

    std::vector<std::string> code = spi::StringSplit(m_verbatim.str(), '\n');
    m_verbatim.str(std::string());

    return Verbatim::Make(filename, lineNumber, code);
}

int ConfigLexer::getLineNumber() const
{
    return yylineno;
}


