# cygwin64_config.mk

G_BASE_CONFIG:=cygwin64_gcc

ifdef COMPILER
G_BASE_CONFIG:=cygwin64_$(COMPILER)
endif

G_CONFIG_COMPILER?=gcc
G_CONFIG_COMPILER_BITS?=64
G_CONFIG_COMPILER_ABI?=Release-cygwin64

