target:

U_SPI_HOME=..

include $(U_SPI_HOME)/makefiles/config/config.mk

U_SRC_DIR=src
U_INC_DIR=isda

U_TARGET=isda-util

U_FORCE_REBUILD=Makefile
U_OBJS=\
cerror.$(G_OBJ)\
cfileio.$(G_OBJ)\
cmemory.$(G_OBJ)\
convert.$(G_OBJ)\
dateconv.$(G_OBJ)\
lprintf.$(G_OBJ)\
lscanf.$(G_OBJ)


include $(U_SPI_HOME)/makefiles/build/lib.mk

