pyd:

U_SPI_HOME=../..
include $(U_SPI_HOME)/makefiles/config/config.mk

U_INSTALL_FILES=$(G_SPI_DLLS)\
$(G_INSTALL_DLL_PFX)spi_replay$(G_INSTALL_DLL_EXT)\
$(G_INSTALL_PYD_PFX)py_spi_replay$(G_INSTALL_PYD_EXT)

U_VCPROJ_OPTIONS=-S .

include $(U_SPI_HOME)/makefiles/spi/pyd.mk


